[project]
name = "conv-ai-llms"
version = "0.1.0"
description = "Общее окружение для лабораторных работ"
requires-python = ">=3.10,<3.13"
dependencies = [
    "datasets==2.19.1",
    "ipykernel==6.29.4",
    "jupyterlab==4.2.1",
    "matplotlib==3.8.4",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "scikit-learn==1.4.2",
    "torch==2.2.2",
    "transformers==4.40.2",
]

[tool.uv]
package = false
